version: '2.0'

services:

   kafka:
      image: daki/kafka
      container_name: kafka
      hostname: kafka
      ports:
         - "2181:2181"
         - "9001:9001"
         - "192.168.2.38:9092/tcp:9092/tcp"
         - "192.168.2.38:9001/tcp:9001/tcp"

      network_mode: "host"

      extra_hosts:
         kafka: 192.168.2.38

      volumes:
        - /var/docker/kafka/c1/log/zookeeper:/var/log/zookeeper
        - /var/docker/kafka/c1/data:/tmp/kafka-logs
        - /var/docker/kafka/c1/log/kafka:/var/log/kafka-logs

      environment:
         - DEBUG=1
         - CONSUMER_THREADS=1
         - TOPICS=myTopic,syslog
         - BROKER_ID=1
         - ZK_CONNECT=kafka7zookeeper:2181/root/path
         - ADVERTISED_PORT=9092
         - ADVERTISED_HOST=192.168.2.38
         - LOG_RETENTION_HOURS=1
         - ZOO_LOG_DIR=/var/log/zookeeper
         - KAFKA_JMX_OPTS=-Djava.rmi.server.hostname=192.168.2.38 -Djava.net.preferIPv4Stack=true -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false  -Dcom.sun.management.jmxremote.ssl=false
         - JMX_PORT=9001

